/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_java3;

/**
 *
 * @author JOSEPH
 */
public class Frm_Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Prueba
     */
    public Frm_Prueba() {
        initComponents();
    }
    
    public void MostrarPadre(Padre p){
        txtMostrar.setText(null);
        String mensaje = p.verMensaje();
        txtMostrar.append(mensaje+"\n");
        txtMostrar.append("NOMBRE: "+p.getNombre()+"\n");
        txtMostrar.append("EDAD: "+p.getEdad()+"\n");
        txtMostrar.append("SUELDO: "+p.getSueldo()+"\n");

    }
    
    public void MostrarHija(Hija h){
        txtMostrar.setText(null);
        String mensaje = h.verMensaje();
        txtMostrar.append(mensaje+"\n");
        txtMostrar.append("NOMBRE: "+h.getNombre()+"\n");
        txtMostrar.append("EDAD: "+h.getEdad()+"\n");
        txtMostrar.append("SUELDO: "+h.getSueldo()+"\n");
        txtMostrar.append("CARRERA: "+h.getCarrera()+"\n");

    }
    
    public void MostrarNieta(Nieta n){
        txtMostrar.setText(null);
        String msj= n.verMensaje();
        txtMostrar.append(msj+"\n");
        txtMostrar.append("NOMBRE: "+n.getNombre()+"\n");
        txtMostrar.append("EDAD: "+n.getEdad()+"\n");
        txtMostrar.append("SUELDO: "+n.getSueldo()+"\n"); // no heredo este atributo de hija
        txtMostrar.append("CARRERA: "+n.getCarrera()+"\n");
        txtMostrar.append("MÚSICA"+n.getMusica());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPadre = new javax.swing.JButton();
        btnHija = new javax.swing.JButton();
        btnNieta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPadre.setText("Padre");
        btnPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadreActionPerformed(evt);
            }
        });

        btnHija.setText("Hija");
        btnHija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijaActionPerformed(evt);
            }
        });

        btnNieta.setText("Nieta");
        btnNieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNietaActionPerformed(evt);
            }
        });

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNieta)
                    .addComponent(btnHija)
                    .addComponent(btnPadre))
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnPadre)
                .addGap(18, 18, 18)
                .addComponent(btnHija)
                .addGap(26, 26, 26)
                .addComponent(btnNieta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadreActionPerformed
        // TODO add your handling code here:
        Padre p1= new Padre("Juan",56,1800);
        
        
        MostrarPadre(p1);

        
    }//GEN-LAST:event_btnPadreActionPerformed

    private void btnHijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijaActionPerformed
        // TODO add your handling code here:
        Hija h1= new Hija("Maria",26,3500.0,"Ingeniería");
        MostrarHija(h1);

    }//GEN-LAST:event_btnHijaActionPerformed

    private void btnNietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNietaActionPerformed
        // TODO add your handling code here:
        Nieta n1= new Nieta("LUCIA",18,"MEDICINA","BALADAS");
        MostrarNieta(n1);

    }//GEN-LAST:event_btnNietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHija;
    private javax.swing.JButton btnNieta;
    private javax.swing.JButton btnPadre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables
}
